### ISSUE TITLE
Refactor TodoTxt to decouple from files

### ISSUE THREAD

**Issue by vonshednob** [vonshednob/pytodotxt#7]
`TodoTxt` currently fulfills two purposes: as the container for `Tasks`s grouped in a file and as the dispatcher to parse `Task`s from a file.

These two responsibilities should be split to allow for easier extension.

**Comment by Sylvain303** [comment]
Hello, 

I also noticed that if `lines` , I mean `str(task)` can get accessed directly through some API in `pytodotxt.TodoTxt` (reading and writing) via some methods,  I can also reuse your `TodoTxt.save()` to save my own lines reusing your code for handling `target` `safe` `linesep`. Here is the modified code in an extended class I made from `TodoTxt` (aka the container and file writer) (the code of `TodoTxt`, [is also modified](https://github.com/Sylvain303/pytodotxt/blob/support-subclassing/pytodotxt/todotxt.py#L110) to be extended that way of course):

https://github.com/Sylvain303/tototxt_zim/blob/pytodotxt_get_lines_once/extended_todotxt_todotxt.py#L42-L52

```python
    def get_text_lines(self):
        """Get all Task as list of lines (str)                                                                                                       
        """
        if self.get_lines_once is not None:
            lines = self.get_lines_once
            self.get_lines_once = None
            return lines
        else:
            return super().get_text_lines()
```

compare from #6 and my changes for accessing lines directly

https://github.com/seanbreckenridge/pytodotxt/compare/support-subclassing...Sylvain303:support-subclassing 

As you could see, I'm moving out the code for getting lines from `TodoTxt.tasks` you were doing, a loop inside `TodoTxt.save()`

```python
 lines = [str(task) + linesep for task in
                     sorted(self.tasks, key=lambda t: t.linenr if t.linenr is not None else len(self.tasks))]
```
I suggest to wrap it into a method call:

```python
lines = [ l + linesep for l in self.get_text_lines() ]  
```

**Comment by vonshednob** [comment]
@Sylvain303 Would you be fine with being added to the authors file? You’re providing valuable input and helping a lot here :)

**Comment by Sylvain303** [comment]
> @Sylvain303 Would you be fine with being added to the authors file? You’re providing valuable input and helping a lot here :)

oh, yes. I'm kind of code tourist :smile: going where my fingers brings me.
You drive, that's your project. I contribute when I catch some spare time. I don't know yet where I will goes with my code.

I'm actually coding it. So if you've some spare time too, let's hack your code.

**Comment by vonshednob** [comment]
Alright, stuff happened in the new [1.4.0 release](https://github.com/vonshednob/pytodotxt/tree/v1.4.0).

@Sylvain303 you probably want to use [TodoTxt.lines](https://vonshednob.cc/pytodotxt/doc/reference.html#pytodotxt.TodoTxt.lines); let me know if I missed a point, so I can provide more code snippets.

@seanbreckenridge I changed the API a bit, compared to your pull request. Have a look at the [subclassing example](https://vonshednob.cc/pytodotxt/doc/examples.html#have-your-own-custom-task-subclass) to get your use-case covered.

And in general, have a look at the [TodoTxtParser](https://vonshednob.cc/pytodotxt/doc/reference.html#todotxtparser), which supports parsing todo.txt-tasks from all kinds of sources.

**Comment by seanbreckenridge** [comment]
[Works great](https://github.com/seanbreckenridge/HPI/commit/93135b9bf2286c539142bb9bb3dd633f3841396c), thanks 💙

```
$ hpi doctor -S my.todotxt.file_backups
✅ OK  : my.todotxt.file_backups
✅     - stats: {'todos': {'count': 1}, 'completed': {'count': 261}, 'events': {'count': 1847, 'last': datetime.datetime(2022, 2, 20, 8, 54, 39)}}
$ hpi query my.todotxt.file_backups.todos -s -o pprint
Todo('(C) 2022-02-17 add +music to playlists')
```

**Comment by Sylvain303** [comment]
Hi @vonshednob 

I'm testing it. Some improvement suggestion already

* (cosmetic) back link from the generated doc to the code (example: when I'm watching [Todotxt.add()](https://vonshednob.cc/pytodotxt/doc/reference.html#pytodotxt.TodoTxt.add) would be cool if I can see the [code](https://github.com/vonshednob/pytodotxt/blob/v1.4.0/pytodotxt/todotxt.py#L40))  
* (behavior change) missing end-of-line on the last line, `TodoTxt.save()` was added on the last line in v1.3.0, `vim` and `cat` and `git` likes last end of line NL character, was ensured by `lines = [ l + linesep for l in convert_tasks_to_lines_of_str ]` [write_to_stream()](https://github.com/Sylvain303/pytodotxt/blob/5e5ff239bab5703e2a95902bec3b8976b3cfb2c7/pytodotxt/todotxt.py#L129) don't do that, `str.join()` dont prepend the sep after the last item

I'm not successful rewrite my parser actually, it's WIP.
I did sub-class `pytodotxt.TodoTxtParser` to support parsing from lines, but don't figure out yet how to call it from the container `pytodotxt.TodoTxt.parse()` which still handle filename. I will sub-class it too to allow parse from lines (`list(str)`).

After that I will try to wrap my Zim page sub-section parsing into a io stream object, I will compare if it becomes more code writing or less. :wink:  

Thanks for the update.
I'm still testing...
https://github.com/Sylvain303/tototxt_zim/blob/wip_support_v1.4.0/todotxt.py#L55-L57

Out of time for this morning... :hourglass:

**Comment by vonshednob** [comment]
Hm, I like the idea of back-linking; I’ll see how I can accomplish that.

The behaviour change is something that did not actually sneak itself in - I was very much aware of it; but I think you’re right, it’s an undocumented change and probably actually somehow a bug :sweat_smile:

**Comment by Sylvain303** [comment]
Do you want me to open new issue(s) may be, instead of commenting in this closed one?

So, I'm continuing, but can't manage yet to sub-class `pytodotxt.TodoTxt`  and get my override of `lines()` working.

I corrected [the missing end-of-line bug in my fork](https://github.com/Sylvain303/pytodotxt/commit/275df0beed6bc927728447c9bfd5310af1df01fe)

But my subclass don't work any more, there's a trick I can't get yet with the `pytodotxt.TodoTxt.lines` and the property decorator and or the method.

I got some errors like: `TypeError: 'method' object is not iterable` or `TypeError: can only join an iterable`

here is the [sub-class pytodotxt.TodoTxt prototype](https://github.com/Sylvain303/tototxt_zim/blob/wip_support_v1.4.0/extended_todotxt_todotxt.py#L9):

```python
    # Our lines() allows to override input list with our lines if get_lines_once is set.
    # Used to call our save() with lines as extra argument.
    def lines(self):
        """Get all Task as list of lines (str)
        """
        if self.get_lines_once is not None:
            lines = self.get_lines_once
            self.get_lines_once = None
            return lines
        else:
            return super().lines()     
```
I did succeed by removing the decorator `@property` on your `lines()` and using method call everywhere instead of property ~~`instance.lines`~~ ==>   `instance.lines()`

```diff
diff --git a/pytodotxt/todotxt.py b/pytodotxt/todotxt.py
index bed258c..7e27315 100644
--- a/pytodotxt/todotxt.py
+++ b/pytodotxt/todotxt.py
@@ -126,10 +126,9 @@ class TodoTxt:
         """
         if linesep is None:
             linesep = self.linesep
-        txt = linesep.join(self.lines) + linesep
+        txt = linesep.join(self.lines()) + linesep
         stream.write(bytes(txt, self.encoding))
 
-    @property
     def lines(self):
         """Much like ``self.tasks``, but already sorted by linenr and converted to string"""
         lines = [(task.linenr if task.linenr is not None else len(self.tasks), str(task))
```

May be some answer here: https://stackoverflow.com/questions/7019643/overriding-properties-in-python
It seems a bit overkill for me, I'm in the situation that code reuse involves more code writing than re-coding. 

I'm still experimenting... :wink:

**Comment by Sylvain303** [comment]
So @vonshednob 

I finally tested the IOString version, only using the `pytodotxt.TodoTxtParser` without the container ~~`pytodotxt.TodoTxt`~~. This way it works, it gives me extra step to convert back my array of lines to  stream object, and I don't use container feature for now.

[Non container version + stream read from io.StringIO](https://github.com/Sylvain303/tototxt_zim/blob/wip_support_v1.4.0_no_container/todotxt.py#L55)

```python
todo_parser = pytodotxt.TodoTxtParser(task_type=ZimTask)                                                                                             
io_buffer = zim_todotxt.get_todo_as_StringIO(zim_section)
list_of_tasks = todo_parser.parse(io_buffer)
now = strftime("%Y-%m-%d %H:%M:%S", localtime())
list_of_tasks.append(ZimTask(f"new task {now}"))

print(f"================== list of tasks not completed: {len(list_of_tasks)}")
for t in list_of_tasks:
    if not t.is_completed:
        print(f"{t.linenr}: {t.description}")

    if 'finish him' in t.description:
        t.is_completed = True
        print(f"set_completed: {t.linenr} {t.description}")
```

You didn't provide a way to handle stream in `pytodotxt.TodoTxt` (the container), only filename, right?
To be continued...

**Comment by vonshednob** [comment]
> You didn't provide a way to handle stream in `pytodotxt.TodoTxt` (the container), only filename, right?

Correct. The idea is that you implement your own container if you need other than default todo.txt-file access.

I'll create a new issue for the missing newline.

**Comment by Sylvain303** [comment]
@vonshednob yes, v1.4.1 worked!

By overriding `build_lines()` 

https://github.com/Sylvain303/tototxt_zim/blob/save_lines_v1.4.1/extended_todotxt_todotxt.py#L39

I need to progress a bit more, I may propose more test and sample use-case for the documentation. 

I will let you know in some other issue. :smile:

Thanks.
